# Generated by Django 4.1.3 on 2022-11-13 02:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tractor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=100)),
                ("drivers_seat", models.CharField(max_length=100)),
                ("cab_suspension", models.CharField(max_length=100)),
                ("front_axle_suspension", models.BooleanField()),
                ("wheel_drive", models.CharField(max_length=10)),
                ("gear_box_type", models.CharField(max_length=50)),
                ("implementations", models.TextField()),
                ("rpm", models.IntegerField()),
                ("pto", models.BooleanField()),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
