# Generated by Django 4.1.3 on 2022-11-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("krishikhoj", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tractor",
            name="name",
            field=models.CharField(default="Laal", max_length=300),
            preserve_default=False,
        ),
    ]
