# Generated by Django 4.1.3 on 2022-11-13 09:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("krishikhoj", "0003_remove_tractor_id_tractor_trac_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tractor",
            old_name="name",
            new_name="naming",
        ),
        migrations.AlterField(
            model_name="tractor",
            name="trac_id",
            field=models.UUIDField(
                default=uuid.UUID("c6a2b554-cb61-4212-a794-96d703467231"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
